### PR TITLE
Migrate to Github Actions CI

### PR DESCRIPTION
**Pull request by Altai-man**

### CODE REVIEW

**Comment by jnthn** [comment]
In the `.travis.yml` we had this:

```
    - zef install https://github.com/croservices/cro-core/archive/master.zip
    - zef install https://github.com/croservices/cro-tls/archive/master.zip
```

That is, we force the installation of HEAD of the Cro dependencies, because otherwise if we do a change that depends on an enhancement in `Cro::Core` we'll end up with failing tests. Probably we should replicate that in the GitHub Actions migration for `cro-tls`, `cro-http`, `cro-websocket`, and `cro`.

**Comment by Altai-man** [comment]
Maybe we can just do minor version bumps more often when enhancement happens instead and the users will get updates with fixes instead of bogus situations when the answer is "oh, sorry, you need to install from master, because we do releases very rarely" instead of "zef install and it just works for yoU"?

**Comment by jnthn** [comment]
> Maybe we can just do minor version bumps more often when enhancement happens instead and the users will get updates with fixes instead of bogus situations when the answer is "oh, sorry, you need to install from master, because we do releases very rarely" rather than "zef install and it just works for you"?

We could certainly do releases more often, but that feels like an orthogonal concern. If there's a change in `Cro::Core` and we want to do a coordinated change in `Cro::HTTP`, we want to test against the latest `Cro::Core`, not whatever was last released. Similarly, if there's a regression in `Cro::Core` that only shows up in `Cro::HTTP` then we would like to know about it from the CI. 

> I encountered this situation not once before

Maybe you simply didn't notice it because the CI was set up to handle this. :P At least one change going into the upcoming release has exactly this situation we're describing here, though (the TCP NO_DELAY bits).

> it feels like something like this in CI is a bad practice

How so? It means we're getting feedback on things as they will be in the next release we ship, and matches the synchronized release process we have across core/TLS/HTTP/WebSocket. Note that I'm not advocating this as a thing for CI setups to do *in general*, or even for everything under `croservices`, but just for the set of things that are part of the coordinated release.

**Comment by Altai-man** [comment]
I updated Cro::TLS to https://github.com/croservices/cro-tls/pull/6/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR28 get latest Cro::Core and will do as you recommend with other repos.

This being told,

>Maybe you simply didn't notice it because the CI was set up to handle this

Sorry, I did not phrase the idea correctly. What I was saying is that there were certainly cases when the fixes were present on master, but without a version bump zef would go with the old version, people get bugs, complain and the answer is "just install it from master for now".

If there is a simultaneous change in Cro::Core and Cro::HTTP, why not merge Cro::Core first, bump and then test Cro::HTTP that will work after a bump? One might argue "But how can we merge Cro::Core not being sure it works well with Cro::HTTP first", but it is already checked by the patch dev or that's what I'd assume.

**Comment by jnthn** [comment]
>  it is already checked by the patch dev or that's what I'd assume

Maybe, but only "on my machine", which carries dangers like forgetting to `add` a file, seeing the failure, and assuming it's just out-of-sync. Having Windows/MacOS checked is also useful (once we get the Windows deps issues sorted out).

**Pull request merged**
