### PR TITLE
Implement an easier way to use custom methods

### PR DESCRIPTION
**Pull request by Altai-man**

### CODE REVIEW

**Comment by Altai-man** [comment]
```
➜  cro-http git:(custom-methods) perl6 -Ilib t/http-custom-methods.t 
ok 1 - GET using http method works
ok 2 - Body text is correct
ok 3 - CUSTOM using http method works
ok 4 - Body text is correct
ok 5 - GET using http method works
ok 6 - Body text is correct
ok 7 - CUSTOM using http method works
ok 8 - Body text is correct
1..8
```

I wonder if travis cannot handle HTTP/2 because of ALPN support absence.

**Comment by jnthn** [comment]
Ah, that'd explain it, yes. But that'd hit any other users in the same situation. I suggest checking if we have ALPN support and skipping the tests if not, as we do elsewhere.

**Comment by Altai-man** [comment]
IO::Socket::Async breaks builds.

**Comment by jnthn** [comment]
Yeah, I'm guessing - since it only happens on an older version of Rakudo - that it relates to a Rakudo bug that got fixed.

**Pull request merged**
